version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "daily"
