version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "js"

  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "android"
