version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "🛠 dependencies"
  - package-ecosystem: "gradle"
    directory: "/package/android/"
    schedule:
      interval: "weekly"
    labels:
      - "🛠 dependencies"
      - "🤖 android"
  # - package-ecosystem: "npm"
  #   directory: "/package/"
  #   schedule:
  #     interval: "monthly"
  #   labels:
  #     - "🛠 dependencies"
  #     - "☕️ js"
  # - package-ecosystem: "npm"
  #   directory: "/package/example/"
  #   schedule:
  #     interval: "monthly"
  #   labels:
  #     - "🛠 dependencies"
  #     - "🛸 example"
  #     - "☕️ js"
  # - package-ecosystem: "npm"
  #   directory: "/docs/"
  #   schedule:
  #     interval: "monthly"
  #   labels:
  #     - "🛠 dependencies"
  #     - "📚 documentation"
  #     - "☕️ js"
