blank_issues_enabled: false
contact_links:
  - name: Troubleshooting Guide
    url: https://react-native-vision-camera.com/docs/guides/troubleshooting
    about: Please read the Troubleshooting Guide before opening an issue.
  - name: VisionCamera Discussions
    url: https://github.com/mrousavy/react-native-vision-camera/discussions
    about: Please ask and answer questions here.
  - name: Google's CameraX Issue Tracker
    url: https://issuetracker.google.com/issues?q=componentid:618491%20status:open#
    about: Please post issues about the native Android Camera Library (CameraX) here.
