name: ❓ Question
description: Ask a Question about this library
title: "❓ "
labels: [❓ question]
body:
  - type: textarea
    attributes:
      label: Question
      description: Ask a question about the library or ask for help/advice. Make sure to be as detailed as possible, since well written questions are more likely to be picked up than badly written ones.
      placeholder: How do I take a photo?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What I tried
      description: (Optional) Explain what alternatives/workarounds you tried.
      placeholder: I tried to use `Camera.takePhoto()`
  - type: input
    attributes:
      label: VisionCamera Version
      description: Which version of react-native-vision-camera are you using?
      placeholder: ex. 2.0.1-beta.1
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Additional information
      description: Please check all the boxes that apply
      options:
        - label: I am using Expo
        - label: I have read the [Troubleshooting Guide](https://react-native-vision-camera.com/docs/guides/troubleshooting)
          required: true
        - label: I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.
          required: true
