name: Validate Swift

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/validate-swift.yaml"
      - "ios/"
      - "example/ios/"
  pull_request:
    paths:
      - ".github/workflows/validate-swift.yaml"
      - "ios/"
      - "example/ios/"

jobs:
  SwiftLint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
        env:
          # DIFF_BASE: ${{ github.base_ref }}
          WORKING_DIRECTORY: ios
  # TODO: Figure out how to run SwiftFormat in a GitHub action
  # SwiftFormat:
  #   name: SwiftFormat
  #   description: 'https://github.com/nicklockwood/SwiftFormat'
  #   runs-on: ubuntu-latest
  #   env:
  #     working-directory: ./ios
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Format Swift code
  #       run: swiftformat --verbose .
  #       working-directory: ${{env.working-directory}}

  #     - name: Verify formatted code is unchanged
  #       run: git diff --exit-code HEAD
  #       working-directory: ${{env.working-directory}}
